#========================
# lazy plugin settings
#========================

#----------------
# denite
#----------------
[[plugins]] # denite
if = '''has('nvim')'''
repo = 'Shougo/denite.nvim'
on_cmd = 'Denite'
hook_add = 'source ${HOME}/.config/nvim/userautoload/plugins/denite_add.vim'
hook_post_source = 'source ${HOME}/.config/nvim/userautoload/plugins/denite_source.vim'
[[plugins]] # Plugin to easily access Most Recently Used (MRU) files
repo = 'Shougo/neomru.vim'
on_source = 'denite.nvim'
on_path = '.*'
# hook_add = '''
# let g:neomru#follow_links = 1
# '''
[[plugins]] # Yank
repo = 'Shougo/neoyank.vim'
# [[plugins]]
# repo = 'nixprime/cpsm'
# build = 'env PY3=ON ./install.sh'
# [[plugins]] # neoyank
# repo = 'Shougo/neoyank.vim'

#--------------
# 補完
#--------------
[[plugins]] # deoplete
if = '''has('nvim')'''
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
source ~/.config/nvim/userautoload/plugins/deoplete.vim
'''
hook_post_source = '''
let g:deoplete#omni_patterns = {}
'''
[[plugins]] # for c,cpp
repo = 'zchee/deoplete-clang'
depends = 'deoplete.nvim'
on_ft = ['c', 'c11', 'cpp', 'cc', 'cmake', 'C']
on_i = 1
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/opt/local/libexec/llvm-5.0/lib/libclang.dylib'
let g:deoplete#sources#clang#clang_header = '/opt/local/libexec/llvm-5.0/lib/clang'
'''
[[plugins]] # for python
repo = 'zchee/deoplete-jedi'
depends = 'deoplete.nvim'
on_ft = ['python','py']
on_i = 1
hook_source = '''
let g:deoplet#sources#jedi#python_path = '/opt/local/bin/python3.6'
'''

#--------------
# Ale
#--------------
[[plugins]] # syntax checker
repo = 'w0rp/ale'
hook_add  = 'source ~/.config/nvim/userautoload/plugins/ale.vim'

#-------------
# quickrun
#-------------
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = ' source ~/.config/nvim/userautoload/plugins/quickrun.vim'

#------------
# NERDTree
#------------
[[plugins]] # NERDTree
repo = 'scrooloose/nerdtree'
hook_add = 'source ~/.config/nvim/userautoload/plugins/nerdtree.vim'
[[plugins]] # NERDTree tabs
repo = 'jistr/vim-nerdtree-tabs'
# [[plugins]] # NERDTree highlight
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# depends = ['nerdtree']
# hook_post_source = 'source ~/.config/nvim/userautoload/plugins/nerdtree-highlight.vim'

#-----------------
# Tagbar
#-----------------
[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = 'source ~/.config/nvim/userautoload/plugins/tagbar.vim'

#------------
# snippet
#------------
[[plugins]] # neosnippet
repo = 'Shougo/neosnippet.vim'
depends = 'neosnippet-snippets'
on_i  = 1
hook_add = 'source ~/.config/nvim/userautoload/plugins/neosnippet.vim'
# on_ft = 'snippet'

#------------
# markdown
#------------
[[plugins]] # markdown
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown','md','mkd']
hook_post_source = '''
let g:vim_markdown_folding_disabled=1
'''
[[plugins]] # preview markdown in browser
repo = 'kannokanno/previm'
hook_add = 'source ~/.config/nvim/userautoload/plugins/previm.vim'
on_ft = ['markdown','md','mkd']
[[plugins]] # openbrowser
repo = 'tyru/open-browser.vim'
on_ft = ['markdown','md','mkd']
# hook_source = '''
# let g:netrw_nogx = 1
# nmap gx <Plug>(openbrowser-smart-search)
# vmap gx <Plug>(openbrowser-smart-search)
# let g:previm_open_cmd = 'open -a Safari'
# '''
[[plugins]] # 表作成 for markdown
repo = 'dhruvasagar/vim-table-mode'
on_ft = ['markdown','md','mkd']
hook_post_source = '''
let g:table_mode_corner='|'
'''

#-------------------------------------------

[[plugins]] #  comment-out
repo = 'tomtom/tcomment_vim'
hook_add = 'source ~/.config/nvim/userautoload/plugins/tcomment.vim'

[[plugins]] # capture vim command results
repo = 'tyru/capture.vim'

[[plugins]] # ヘルプ日本語化
repo = 'vim-jp/vimdoc-ja'
hook_post_source = '''
set helplang=ja,en
'''

[[plugins]] # サイズ変更
repo = 'simeji/winresizer'
hook_add = '''
nno <C-E> <Nop>
nno <C-E> :WinResizerStartResize<CR>
'''

[[plugins]] # Toml syntax
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo  = 'junegunn/limelight.vim'
hook_add=' source ${HOME}/.config/nvim/userautoload/plugins/limelight.vim'
[[plugins]]
repo  = 'junegunn/goyo.vim'
hook_add=' source ${HOME}/.config/nvim/userautoload/plugins/goyo.vim'

