#======================
# plugin settings file
#======================

#----------
# Dein
#----------
[[plugins]] # plugin管理
repo = 'Shougo/dein.vim'

#----------
# Vimproc
#----------
[[plugins]] # 非同期処理
# name = 'vimproc'
repo = 'Shougo/vimproc.vim'
build = 'make'

#-----------
# Devicons
#-----------
[[plugins]] # icons
repo = 'ryanoasis/vim-devicons'
hook_add = 'source ~/.config/nvim/userautoload/plugins/devicons.vim'

#-----------
# Airline
#-----------
[[plugins]] # airline
repo = 'vim-airline/vim-airline'
depends = ['vim-ailine-themes']
# depends = ['tagbar', 'vim-fugitive', 'vim-gitgutter']
hook_add = 'source ${HOME}/.config/nvim/userautoload/plugins/airline.vim'
[[plugins]] # airline-themes
repo = 'vim-airline/vim-airline-themes'
depends = 'vim-airline'
[[plugins]] # for git
repo = 'tpope/vim-fugitive'
[[plugins]] # for git
repo = 'airblade/vim-gitgutter'

#----------
# Neoterm
#----------
[[plugins]]
if = 'has("nvim")'
repo = 'kassio/neoterm'
hook_add = 'source ~/.config/nvim/userautoload/plugins/neoterm.vim'

#-----------
# Snippets
#-----------
[[plugins]] # スニペット集
repo = 'Shougo/neosnippet-snippets'

#-------
# Fzf
#-------
[[plugins]] # fzf
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = 'source ~/.config/nvim/userautoload/plugins/fzf.vim'

#-----------
# Template
#-----------
[[plugins]] # template
repo = 'mattn/sonictemplate-vim'
hook_add = '''
let g:sonictemplate_vim_template_dir = '~/.config/nvim/templates'
nno <Leader>s :Template<Space>
'''

#------------
# Polyglot
#------------
[[plugins]] # polyglot
repo  = 'sheerun/vim-polyglot'

#--------------
# Easy-align
#--------------
[[plugins]] # easy-align
repo = 'junegunn/vim-easy-align'
hook_add= '''
xmap ga <Plug>(EasyAlign)
nmap ga <Plug>(EasyAlign)
'''

#--------------
# Surround
#--------------
[[plugins]] # surround
repo = "tpope/vim-surround"
[[plugins]] # repeat
repo  = 'tpope/vim-repeat'

#--------------
# Colorscheme
#--------------
[[plugins]]
repo = 'tomasr/molokai'
[[plugins]]
repo = 'reedes/vim-colors-pencil'
[[plugins]]
repo = 'cocopon/iceberg.vim'
[[plugins]]
repo = 'lifepillar/vim-solarized8'
[[plugins]]
repo = 'aereal/vim-colors-japanesque'
[[plugins]]
repo = 'nightsense/snow'

#--------------
# Operator
#--------------
# [[plugins]]
# repo = 'kana/vim-operator-user'

#-------------------------------------------
